### ISSUE TITLE
[INFO] Work with RHEL 8.2 and PT 7.3.1

### ISSUE THREAD

**Issue by benyaminl** [thiagoojack/packettracer_ce8#1]
Thank you for providing a great script!

It's working on RHEL 8.2 with PT 7.3.1 (as I wrote this text)
![image](https://user-images.githubusercontent.com/2817332/95569166-68b02300-0a4f-11eb-9a14-91c282dc93b2.png)

**Comment by thiagoojack** [comment]
It is an immense pleasure. Thanks!
